name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Publish to crates.io
      run: |
        # Publish core first, then other crates
        cargo publish -p adyen-core --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        sleep 10
        cargo publish -p adyen-checkout --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        sleep 10
        cargo publish -p adyen-payments --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        sleep 10
        cargo publish -p adyen-webhooks --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        sleep 10
        cargo publish -p adyen --token ${{ secrets.CARGO_REGISTRY_TOKEN }}